# Generated by Django 3.1.1 on 2020-09-22 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('theme_image', models.FileField(null=True, upload_to='products')),
                ('create_at', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default=None, null=True, upload_to='DetailImage')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_products.imagesproducts')),
            ],
        ),
    ]
