# Generated by Django 3.1.1 on 2020-09-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200, null=True)),
                ('description', models.TextField(default=None, max_length=1000, null=True)),
                ('images', models.ImageField(upload_to='videos')),
                ('create_at', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
